# Generated by Django 3.1.5 on 2021-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210125_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='iInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_fname', models.CharField(blank=True, max_length=30)),
                ('i_lname', models.CharField(blank=True, max_length=30)),
                ('i_email', models.EmailField(max_length=254, unique=True)),
                ('i_contact', models.CharField(blank=True, max_length=10)),
                ('i_msg', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
